version: '3.6'
services:
  jenkins:
    container_name: jenkins-dev
    build:
      context: ""
      dockerfile: Dockerfile
    image: jenkins-dev
    ports:
      - "8080:8080"
    networks:
      - jenkins
    command: /etc/init.d/jenkins start

networks:
  jenkins:
