---
- name: Create custom provision scripts directory.
  file:
    path: "{{ jenkins_home }}/provision"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  tags: add_user, add_global_env

- name: List plugins
  jenkins_script:
    script: 'println(Jenkins.instance.pluginManager.plugins)'
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"

- template:
    src: set_global_env_vars.groovy.j2
    dest: "{{ jenkins_home }}/provision/set_global_env_vars.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0755
  tags: add_global_env

- name: Execute scripts Global env vars
  jenkins_script:
    script: "{{ lookup('file', '{{ jenkins_home }}/provision/set_global_env_vars.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}"
    validate_certs: no
  ignore_errors: yes
  tags: add_global_env

- template:
    src: add_user.groovy.j2
    dest: "{{ jenkins_home }}/provision/add_user.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0755
  tags: add_user

- name: Add user
  jenkins_script:
    script: "{{ lookup('file', '{{ jenkins_home }}/provision/add_user.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}"
    validate_certs: no
  ignore_errors: yes
  tags: add_user

- name: interacting with an untrusted HTTPS connection
  jenkins_script:
    script: "println(Jenkins.instance.pluginManager.plugins)"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}"
    validate_certs: no
  ignore_errors: yes
  tags: list_plugins
