---
- name: Check if jenkins_init_default_file exists.
  stat:
    path: "{{ jenkins_init_default_file }}"
  register: jenkins_init_default_file_stat

- name: Ensure jenkins_init_default_file exists.
  file:
    path: "{{ jenkins_init_default_file }}"
    state: touch
  when: not jenkins_init_default_file_stat.stat.exists

- name: Change variables in jenkins_init_default_file
  lineinfile:
    dest: "{{ jenkins_init_default_file }}"
    insertafter: '^{{ item.option }}='
    regexp: '^{{ item.option }}=\"\${{ item.option }} '
    line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
    state: present
  loop: "{{ jenkins_init_default_changes }}"
  register: jenkins_init_default_change_prefix

- name: Set Jenkins home directory
  lineinfile:
    dest: "{{ jenkins_init_default_file }}"
    regexp: '^JENKINS_HOME=.*'
    line: 'JENKINS_HOME={{ jenkins_home }}'
  register: set_jenkins_home

- name: Immediately restart Jenkins on init config changes.
  service:
    name: jenkins
    state: restarted
  when: jenkins_init_default_change_prefix.changed

- name: Set Jenkins HTTP port
  lineinfile:
    dest: "{{ jenkins_init_default_file }}"
    regexp: '^ĤTTP_PORT=.*'
    line: 'HTTP_PORT={{ jenkins_http_port }}'
  register: set_jenkins_http_port

- name: Create custom init scripts directory.
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Trigger handlers immediately in case Jenkins was installed
  meta: flush_handlers

- name: configure default users
  template:
    src: basic-security.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  register: jenkins_users_config

- name: Immediately restart Jenkins on http or user changes.
  service:
    name: jenkins
    state: restarted
  when: >
    (jenkins_users_config is defined and jenkins_users_config.changed)
    or (set_jenkins_http_port is defined and set_jenkins_http_port.changed)
    or (set_jenkins_home is defined and set_jenkins_home.changed)
