---
- apt_key:
   url: https://pkg.jenkins.io/debian/jenkins.io.key
   state: present

- name: Add Jenkins apt repository.
  apt_repository:
   repo: "deb {{ jenkins_repo_url }}"
   state: present
   update_cache: true
  when: jenkins_repo_url != ''

- name: Install Jenkins
  apt:
    name: "jenkins"
    state: latest
    update_cache: true
    autoclean: yes
